version: '3'

services:
  app:
    environment:
      - STRATEGY_URL=http://192.168.1.20:8091
      - ENV=PROD
    volumes:
      - './app:/usr/src/app'
    build: ./app
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80