from mapping.t17001 import T17001

def test_t17001():
    ps1 = T17001()
    ps1.transform('仲小梅','321284198501083626','15052304168')
    assert ps1.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 0, 'td_tel_risk_l': 1, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 1, 'td_idno_veh': 0, 'td_idno_risk_m': 0, 'td_idno_risk_l': 1, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 1, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 2, 'td_apply_1m': 3, 'td_apply_3m': 5, 'td_apply_6m': 5, 'td_apply_12m': 6, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}

    ps2 = T17001()
    ps2.transform('丁炎滨','370983199111010012','13761955305')
    assert ps2.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 0, 'td_tel_risk_l': 0, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 0, 'td_idno_veh': 0, 'td_idno_risk_m': 0, 'td_idno_risk_l': 0, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 0, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 0, 'td_apply_1m': 0, 'td_apply_3m': 0, 'td_apply_6m': 0, 'td_apply_12m': 0, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}

    ps3 = T17001()
    ps3.transform('万国梁', '360123198508011930','18516326459')
    assert ps3.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 0, 'td_tel_risk_l': 0, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 0, 'td_idno_veh': 0, 'td_idno_risk_m': 0, 'td_idno_risk_l': 0, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 0, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 0, 'td_apply_1m': 0, 'td_apply_3m': 0, 'td_apply_6m': 0, 'td_apply_12m': 0, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}

    ps4 = T17001()
    ps4.transform('云高琼', '422826198009300047','15347020567')
    assert ps4.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 1, 'td_tel_risk_l': 0, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 0, 'td_idno_veh': 0, 'td_idno_risk_m': 1, 'td_idno_risk_l': 0, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 0, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 0, 'td_apply_1m': 3, 'td_apply_3m': 6, 'td_apply_6m': 6, 'td_apply_12m': 11, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}

    ps5 = T17001()
    ps5.transform('何淼君', '332621197205058252','13117174542')
    assert ps5.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 0, 'td_tel_risk_l': 0, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 0, 'td_idno_veh': 0, 'td_idno_risk_m': 0, 'td_idno_risk_l': 0, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 0, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 0, 'td_apply_1m': 0, 'td_apply_3m': 0, 'td_apply_6m': 0, 'td_apply_12m': 0, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}

    ps6 = T17001()
    ps6.transform('余瑞泉', '350623198102251016','13817853005')
    assert ps6.variables == {'td_tel_small': 0, 'td_tel_virtual': 0, 'td_tel_fraud': 0, 'td_tel_risk_m': 0, 'td_tel_risk_l': 0, 'td_tel_veh': 0, 'td_tel_debt': 0, 'td_tel_repay': 0, 'td_idno_crime': 0, 'td_idno_exec': 0, 'td_idno_end': 0, 'td_idno_veh': 0, 'td_idno_risk_m': 0, 'td_idno_risk_l': 0, 'td_idno_debt': 0, 'td_idno_tax': 0, 'td_idno_tax_rep': 0, 'td_idno_repay': 0, 'td_risk_tel_hit_ovdu': 0, 'td_risk_tel_hit_high_att': 0, 'td_risk_idc_hit_ovdu': 0, 'td_risk_idc_hit_court_dish': 0, 'td_risk_idc_hit_high_att': 0, 'td_bah_1d_dev_rel_tel': 0, 'td_bah_1d_dev_rel_idc': 0, 'td_bah_1d_idc_rel_dev': 0, 'td_bah_1d_tel_rel_dev': 0, 'td_bah_7d_dev_app': 0, 'td_bah_7d_idc_app': 0, 'td_bah_7d_tel_app': 0, 'td_bah_7d_dev_rel_idc': 0, 'td_bah_7d_dev_rel_tel': 0, 'td_bah_7d_idc_rel_dev': 0, 'td_bah_7d_tel_rel_dev': 0, 'td_bah_1m_dev_app': 0, 'td_bah_1m_idc_app': 0, 'td_bah_1m_tel_app': 0, 'td_bah_1m_idc_rel_dev': 0, 'td_bah_3m_add_rel_idc': 0, 'td_bah_3m_bcname_rel_idc': 0, 'td_bah_3m_idc_rel_add': 0, 'td_bah_3m_idc_rel_tel': 0, 'td_bah_3m_idc_rel_bctel': 0, 'td_bah_3m_idc_rel_mail': 0, 'td_bah_3m_tel_rel_bctel': 0, 'td_bah_3m_mail_rel_idc': 0, 'td_bah_3m_tel_rel_idc': 0, 'td_apply_7d': 0, 'td_apply_1m': 0, 'td_apply_3m': 0, 'td_apply_6m': 0, 'td_apply_12m': 0, 'td_risk_age_high': 0, 'td_idc_name_hit_dish_vague': 0, 'td_idc_name_hit_exec_vague': 0, 'td_applicant_idc_3m_morethan2': 0, 'td_applicant_tel_3m_morethan2': 0}